version: '3'
services:
  kilem-midi:
    build: .
    container_name: kilem-midi
    depends_on:
      - "kilem-mysql"
      - "kilem-redis"
    networks:
      - "kilem-midi"
  kilem-nginx:
    build: ./docker/nginx/
    container_name: kilem-nginx
    depends_on:
      - "kilem-midi"
    ports:
      - 80:80
    networks:
      - "kilem-midi"
  kilem-mysql:
    build: ./docker/mysql
    container_name: kilem-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="ture"
    networks:
      - "kilem-midi"
  kilem-redis:
    image: "redis:alpine"
    container_name: kilem-redis
    networks:
      - "kilem-midi"
networks:
  kilem-midi:
    name: kilem-midi
  